### ISSUE TITLE
Can not install bitbucket cli extension

### ISSUE THREAD

**Issue by ssmogos** [Axway/unified-catalog-integrations#37]
Error received while installing bitbucket cli extension from https://github.com/Axway/unified-catalog-integrations/tree/APIGOV-16590/bitbucket/bitbucket-extension

Using branch:

`4343 silly lifecycle @axway/amplify-central-bitbucket-extension@0.0.1-dev.1~postinstall: Returned: code: 1  signal: null
4344 info lifecycle @axway/amplify-central-bitbucket-extension@0.0.1-dev.1~postinstall: Failed to exec postinstall script
4345 timing action:postinstall Completed in 195ms
4346 verbose unlock done using C:\Users\jso1fe\AppData\Roaming\npm-cache\_locks\staging-a1f20a67005f0d81.lock for C:\Users\jso1fe\AppData\Roaming\npm\node_modules\.staging
4347 timing stage:rollbackFailedOptional Completed in 3039ms
4348 timing stage:runTopLevelLifecycles Completed in 40395ms
4349 warn @apidevtools/swagger-parser@10.0.2 requires a peer of openapi-types@>=7 but none is installed. You must install peer dependencies yourself.
4350 verbose stack Error: @axway/amplify-central-bitbucket-extension@0.0.1-dev.1 postinstall: `yarn --only=dev --ignore-scripts && yarn build && node ./postinstall.js`
4350 verbose stack Exit status 1
4350 verbose stack     at EventEmitter.<anonymous> (C:\Tools\nodesjs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
4350 verbose stack     at EventEmitter.emit (events.js:315:20)
4350 verbose stack     at ChildProcess.<anonymous> (C:\Tools\nodesjs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4350 verbose stack     at ChildProcess.emit (events.js:315:20)
4350 verbose stack     at maybeClose (internal/child_process.js:1021:16)
4350 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
4351 verbose pkgid @axway/amplify-central-bitbucket-extension@0.0.1-dev.1
4352 verbose cwd C:\Development\Amplify
4353 verbose Windows_NT 10.0.18363
4354 verbose argv "C:\\Tools\\nodesjs\\node.exe" "C:\\Tools\\nodesjs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@axway/amplify-central-bitbucket-extension"
4355 verbose node v12.18.4
4356 verbose npm  v6.14.6
4357 error code ELIFECYCLE
4358 error errno 1
4359 error @axway/amplify-central-bitbucket-extension@0.0.1-dev.1 postinstall: `yarn --only=dev --ignore-scripts && yarn build && node ./postinstall.js`
4359 error Exit status 1
4360 error Failed at the @axway/amplify-central-bitbucket-extension@0.0.1-dev.1 postinstall script.
4360 error This is probably not a problem with npm. There is likely additional logging output above.
4361 verbose exit [ 1, true ]`

**Comment by ashutosh49** [comment]
For now, we could run `npm i -g yarn` to install `yarn` globally as a workaround.
We'll address this in the next release.

**Comment by ssmogos** [comment]
Got confirmation that installing yarn solved the problem. 
Customers could not continue on the next step as he is on vacation. We're also waiting for the bitbuket api version.

**Comment by ssmogos** [comment]
@ashutosh49 , they are using Atlassian Bitbucket  v6.10.0

**Comment by ssmogos** [comment]
new bitbucket extension released. 
No new issue reported for now. 
We'll create new tickets if other issues are found. Thanks for the feedback @ashutosh49
