### ISSUE TITLE
Github Extension: Sample Config Output Incorrect

### ISSUE THREAD

**Issue by dwille-axway** [Axway/unified-catalog-integrations#43]
Description: After installing the GitHub Extension, we provide a sample to setup the extension for use with Central. The command example 

Environment: CentOS 8

Command: $ npm install @axway/amplify-central-github-extension

Command Output:
[INFO]:

Extension Installed: You may now add it to the Central CLI

$ amplify central config set extensions.github-extension /home/axway/node_modules/@axway/amplify-central-github-extension**/node_modules/@axway/amplify-central-github-extension**

Expected Behavior: The static path piece seems to be doubled. It likely should look more like this: amplify central config set extensions.github-extension /home/axway/node_modules/@axway/amplify-central-github-extension

Reproduce: Execute install command and review output.

**Comment by ssmogos** [comment]
Thanks @dwille-axway  for reporting the issue. Issue got fixed in the latest github extension release.
https://www.npmjs.com/package/@axway/amplify-central-github-extension/v/1.0.0
