### ISSUE TITLE
Step 2 about creating integration builder flow is missing documentation

### ISSUE THREAD

**Issue by mangatrai** [Axway/unified-catalog-integrations#5]
Step 3.5 (flow creation) refers to Step 2: Configure Integration Builder flow to update subscriptions and send email notifications which i am not able to find on documentation page. can you guys please let me know where we can find step by step instructions for that?

**Comment by mangatrai** [comment]
master branch has it. i was looking at different branch

**Comment by ssmogos** [comment]
thanks @mangatrai for your question. Please let us know if you run into issues with this or you have further questions.
