### ISSUE TITLE
include-mock-endpoints flag doesn't work

### ISSUE THREAD

**Issue by mangatrai** [Axway/unified-catalog-integrations#6]
When i setup include-mock-endpoints to true or false the behavior is same i.e. considering flag to be set true. which is not accurate behavior. If i remove include-mock-endpoints completely from configs then only flag is considered and APIService yaml generated for api don't contain any mocking endpoint information. Demonstrated this to Seth Toda

**Comment by ssmogos** [comment]
Fix available in https://www.npmjs.com/package/@axway/amplify-central-mulesoft-extension/v/0.0.3-dev.1.
Changes also merged to master.
