### ISSUE TITLE
wrong mocking endpoint generated in APIService yaml file

### ISSUE THREAD

**Issue by mangatrai** [Axway/unified-catalog-integrations#7]
When i run amplify central mulesoft-extension resources generate command, API service yaml file for api registered in mulesoft is generated. If as per my config, value to generate mocking endpoint is set to true then i am expecting yaml file to have a APIServiceInstance and ConsumerInstance spec for mocking endpoints.
However that is not the resulting behavior. I see that Mocking endpoint is just duplicate of actual valid endpoint and Consumer instance is pointing to a wrong API Service Instance. attaching a generated file.

change file extenstion to .yaml

[APIService-petstore-include-mock.txt](https://github.com/Axway/unified-catalog-integrations/files/4926156/APIService-petstore-include-mock.txt)

**Comment by ssmogos** [comment]
Fix available in https://www.npmjs.com/package/@axway/amplify-central-mulesoft-extension/v/0.0.3-dev.1.
Changes also merged to master.
