### ISSUE TITLE
make Mulesoft tenant url config based

### ISSUE THREAD

**Issue by mangatrai** [Axway/unified-catalog-integrations#8]
Extension has anypoint url hard coded to https://anypoint.mulesoft.com however mulesoft anypoint platform support multiregion and tenant url change as the region. e.g. my trial instance is in europe region and have https://eu1.anypoint.mulesoft.com
to make this work, i had to rebuild entire extension which is a lot of work for customer. Better way will be to put tenant url in configuration, similar to how we are  accepting amplify urls.

**Comment by ssmogos** [comment]
Fix available in https://www.npmjs.com/package/@axway/amplify-central-mulesoft-extension/v/0.0.3-dev.1.
Changes also merged to master.
